export {default  as  Navbar } from './components/Navbar'
export {default as Carousel} from './components/Carousel'
export {default as About} from './components/About'
export {default as ImageGallery} from './components/ImageGallery'
export {default as Testimonials} from './components/Testimonials'
export {default as Contact} from  './components/Contact'
export {default as Footer} from './components/Footer'